function [fitresult, gof] = accFitFreeDye(t, y, tauD, numIterations)
%accFit(T,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Oct-2018 11:11:24


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, y );

BesZerosSqr = besselzero(0,numIterations,1).^2;
xi = 4./BesZerosSqr;
Gamma = BesZerosSqr.*pi./(16*tauD);

% Set up fittype and options.
fstring = 'c0*(1';
for i=1:numIterations
    fstring = [fstring '-' num2str(xi(i)) '*exp(-' num2str(Gamma(i)) '*D*(t))'];
end
fstring = [fstring ')+c1*exp(-t/T1)'];
disp(fstring);
ft = fittype( fstring, 'independent', 't', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 -Inf]; % D T1 c0 c1
opts.StartPoint = [100 500 1 0.1]; % D T1 c0 c1

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. t', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel t
ylabel y
grid on


