function [fitresult, gof] = erfcFit2(x, y, t)
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Oct-2018 13:29:28


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y);

% Set up fittype and options.
fstring = ['C0*erfc((x-x0)/(2*sqrt(D*' num2str(t) ')))+c1'];
ft = fittype( fstring, 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 -Inf -Inf];
opts.Robust = 'LAR';
opts.StartPoint = [1 1000 0.01 500];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel y
grid on


