function [fitresult, gof] = ExpFit(z, zz)
%CREATEFIT2(Z,ZZ)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : z
%      Y Output: zz
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Dec-2018 11:08:18


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( z, zz );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 -Inf];
opts.StartPoint = [100 0.01 1];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'zz vs. z', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel z
ylabel zz
grid on


